=begin
Swagger Petstore - OpenAPI 3.0

This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)

The version of the OpenAPI document: 1.0.11
Contact: apiteam@swagger.io
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "address".pluralize.to_sym, id: false do |t|
      t.string :street
      t.string :city
      t.string :state
      t.string :zip

      t.timestamps
    end

    create_table "api_response".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :type
      t.string :message

      t.timestamps
    end

    create_table "category".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name

      t.timestamps
    end

    create_table "customer".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :username
      t.string :address

      t.timestamps
    end

    create_table "order".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.integer :pet_id
      t.integer :quantity
      t.datetime :ship_date
      t.string :status
      t.boolean :complete

      t.timestamps
    end

    create_table "pet".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :category
      t.string :photo_urls
      t.string :tags
      t.string :status

      t.timestamps
    end

    create_table "tag".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :username
      t.string :first_name
      t.string :last_name
      t.string :email
      t.string :password
      t.string :phone
      t.integer :user_status

      t.timestamps
    end

  end
end
